require "music-cache/version"
require "music-cache/levenshtein"
require "music-cache/logger"
require "music-cache/scanner"
require "music-cache/analyzer"
require "music-cache/folder"
require "music-cache/error_set"
require "music-cache/runner"
require "music-cache/database"
# collection tree
require "music-cache/collection"
require "music-cache/artist"
require "music-cache/album"
require "music-cache/track"